#!/bin/sh

# Mount virtual filesystems
mount -t proc none /proc
mount -t sysfs none /sys

# Clear the screen
echo -e "\033[H\033[2J"

# Minimalist ASCII art + welcome message
cat << "EOF"

  __  __       _____  _     _               
 |  \/  |     |  __ \(_)   | |              
 | \  / |_   _| |  | |_ ___| |_ _ __ ___    
 | |\/| | | | | |  | | / __| __| '__/ _ \   
 | |  | | |_| | |__| | \__ \ |_| | | (_) |  
 |_|  |_|\__, |_____/|_|___/\__|_|  \___/   
          __/ |                             
         |___/                              

Booted into MyDistro!
Made by Choubik Houssam

EOF

# Start shell as PID 1
exec /bin/sh
